### ISSUE TITLE
push to clojars

### ISSUE THREAD

**Issue by chhatanidinesh** [liebke/zookeeper-clj#22]
can you push latest changes to clojars

**Comment by MichaelDrogalis** [comment]
@liebke is off for a few days for personal reasons. I'll ping him when he's back.

**Comment by fxposter** [comment]
I'd like to resurrect the issue. :)

**Comment by liebke** [comment]
Pushed version 0.9.4 to Clojars.

**Comment by fxposter** [comment]
Thank you!
